from __future__ import annotations

from typing import Protocol

from polymarket_bot.core.models import Decision, Market, PriceBar, TradePrint, WalletTrade


class MarketDataAdapter(Protocol):
    def fetch_active_markets(self) -> list[Market]: ...
    def fetch_market_metadata(self, market_id: str) -> Market: ...
    def fetch_price_history(self, market_id: str, limit: int = 100) -> list[PriceBar]: ...
    def fetch_trades(self, market_id: str, limit: int = 100) -> list[TradePrint]: ...
    def fetch_rewards_config(self, market_id: str) -> float: ...


class WalletDataAdapter(Protocol):
    def fetch_wallet_trades(self, wallet_id: str, limit: int = 500) -> list[WalletTrade]: ...
    def fetch_wallet_positions(self, wallet_id: str) -> dict[str, float]: ...
    def fetch_wallet_market_exposures(self, wallet_id: str) -> dict[str, float]: ...


class ExecutionAdapter(Protocol):
    def place(self, decision: Decision) -> str: ...
    def cancel(self, order_id: str) -> bool: ...
    def cancel_all(self) -> int: ...


class PortfolioAdapter(Protocol):
    def positions(self) -> dict[str, float]: ...
